window:
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels. If both are zero this
  # setting is ignored.
  dimensions:
    columns: 100
    lines: 85

  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is not scaled by
  # DPI and the specified value is always added at both opposing sides.
  padding:
    x: 1
    y: 0

# Colors
# See: https://github.com/eendroroy/alacritty-theme
schemes:
  solarized_dark: &solarized_dark
    primary:
      background: '0x002b36'
      foreground: '0x839496'
    normal:
      black:   '0x073642'
      red:     '0xdc322f'
      green:   '0x859900'
      yellow:  '0xb58900'
      blue:    '0x268bd2'
      magenta: '0xd33682'
      cyan:    '0x2aa198'
      white:   '0xeee8d5'
    bright:
      black:   '0x002b36'
      red:     '0xcb4b16'
      green:   '0x586e75'
      yellow:  '0x657b83'
      blue:    '0x839496'
      magenta: '0x6c71c4'
      cyan:    '0x93a1a1'
      white:   '0xfdf6e3'

colors: *solarized_dark

font:
  size: 9
  bold:
    family: Source Code Pro
    style: Bold
  normal:
    family: Source Code Pro
    style: Medium
  italic:
    family: Source Code Pro
    style: Medium Italic

bell:
  duration: 0

# Background opacity
background_opacity: 1.0

key_bindings:
  - { key: V,        mods: Control|Shift,       action: Paste                        }
  - { key: C,        mods: Control|Shift,       action: Copy                         }

cursor:
  # Cursor style
  #
  # Values for 'style':
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Block

  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  unfocused_hollow: true
