#!/usr/bin/bash

FAN_RPMS=()
ICON_FAN=""

IFS=$'\n'
for i in $(sensors | grep RPM); do
    RPM=$(echo $i | awk '{print $2}')
    FAN_RPMS+="$ICON_FAN $RPM "
done

# trim trailing whitespace
echo "${FAN_RPMS[@]}" | awk '{$1=$1;print}'
